(define (problem p1)
	(:domain merry)
	(:objects z1 r2 z3 n4 z5 c6 n7 z8 n9 n10 z11 c12 z13 n14 - ball A B C D E F G H I - room hob - hobbit)
	(:init
		(at hob F)
		(color z1 zielony)
		(at z1 A)
		(color r2 rozowy)
		(at r2 B)
		(color z3 zolty)
		(at z3 C)
		(color n4 niebieski)
		(at n4 C)
		(color z5 zielony)
		(at z5 D)
		(color c6 czerwony)
		(at c6 D)
		(color n7 niebieski)
		(at n7 E)
		(color z8 zielony)
		(at z8 E)
		(color n9 niebieski)
		(at n9 F)
		(color n10 niebieski)
		(at n10 F)
		(color z11 zielony)
		(at z11 H)
		(color c12 czerwony)
		(at c12 H)
		(color z13 zolty)
		(at z13 I)
		(color n14 niebieski)
		(at n14 I)
		
		(door A B zolty)
		(door A C czerwony)
		(door C A czerwony)
		(door B D zolty)
		(door C E zielony)
		(door E C zielony)
		(door D F zielony)
		(door F D zielony)
		(door E F niebieski)
		(door F E niebieski)
		(door F G rozowy)
		(door E H czerwony)
		(door H E czerwony)
		(door F I niebieski)
		(door I F niebieski)
		(door H I niebieski)
		(door I H niebieski)
		
		(puzzle A)
		(adjacent box1 box2)
		(adjacent box2 box1)
		(adjacent box1 box4)
		(adjacent box4 box1)
		(adjacent box2 box3)
		(adjacent box3 box2)
		(adjacent box2 box5)
		(adjacent box5 box2)
		(adjacent box3 box6)
		(adjacent box6 box3)
		
		(adjacent box4 box5)
		(adjacent box5 box4)
		(adjacent box4 box7)
		(adjacent box7 box4)
		(adjacent box5 box6)
		(adjacent box6 box5)
		(adjacent box5 box8)
		(adjacent box8 box5)
		(adjacent box6 box9)
		(adjacent box9 box6)
		
		(adjacent box7 box8)
		(adjacent box8 box7)
		(adjacent box8 box9)
		(adjacent box9 box8)
		
		
		(numbered box1 num5)
		(numbered box2 num4)
		(numbered box3 num1)
		(numbered box4 num8)
		(numbered box5 pusty)
		(numbered box6 num3)
		(numbered box7 num7)
		(numbered box8 num2)
		(numbered box9 num6)
		
		)
	
	(:goal
		(and
			(solved A)
			(at hob G)
		)
	)
)